name: glowbloom
description: "Glowbloom — a memory game by TreeAnts Technologies."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
